export const shopCategories = [
  { value: "electronics", label: "Electronics" },
  { value: "fashion", label: "Fashion" },
  { value: "home_appliances", label: "Home Appliances" },
  { value: "books", label: "Books" },
  { value: "sports", label: "Sports" },
  { value: "toys", label: "Toys" },
  { value: "health_and_beauty", label: "Health & Beauty" },
  { value: "automotive", label: "Automotive" },
  { value: "groceries", label: "Groceries" },
  { value: "furniture", label: "Furniture" },
  { value: "jewelry", label: "Jewelry" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "baby_products", label: "Baby Products" },
  { value: "garden_and_outdoor", label: "Garden & Outdoor" },
  { value: "musical_instruments", label: "Musical Instruments" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "handmade", label: "Handmade" },
  { value: "art_and_collectibles", label: "Art & Collectibles" },
  { value: "watches", label: "Watches" },
];
